### ISSUE TITLE
Can this be used in the package.json "transform"?

### ISSUE THREAD

**Issue by yilativ** [smrq/tsify#30]
Hi, 
Can this be plugged into package.json transform node?
   "browserify": {
        "transform": [
            "hbsfy",
            "tsify"
        ]
    }

I'm trying this and it seems to be that the tsify is getting string paths instead of the source stream, even though I've added the vinyl source step before that. 

So has this been successfully used with this set up? Or does the plugin have to be manually added as shown in the main instructions?

**Comment by smrq** [comment]
`tsify` is a Browserify *plugin*, not a *transform*.  This is sort of an implementation detail; transforms are limited in the scope of what they are able to do, and `tsify` needs access to more than what transforms are capable of.  (More details are in the [readme](https://github.com/smrq/tsify#why-a-plugin).)

What that means is that you have to include it as a plugin rather than a transform.  As far as I know, it's not possible to include plugins into your Browserify setup via your `package.json`.  (Again, implementation details here: the `package.json` field is passed along to `substack/module-deps`, which handles transforms on a file-by-file basis.  As far as I know, that field isn't used by Browserify directly at all, so it wouldn't be possible at present for it to set up plugins using it.)

If that's a problem, then perhaps request a feature in the [issues](https://github.com/substack/node-browserify/issues) for `substack/node-browserify`.  Otherwise, you can set it up as detailed in the [readme](https://github.com/smrq/tsify#example-usage).
