### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by cherrydev** [smrq/tsify#38]
When using tsify, I can't seem to catch typescript errors using the standard `.on("error", function() {foo})` idiom.  The only way that I could catch the error was to do it in a domain, which broke `watchify`. So far I've hacked my own version of tsify that allows an error handler to be passed in `opts` and if found, replaces the built-in error-handler.  I don't think this is very node-ish and ideally there should be some way to optionally `this.emit("end")` in the custom error handler, or NOT, but I couldn't find a way to suppress the error if I left the default error handler (that calls `b.pipeline.emit("error", error)`) attached.

Unfortunately I don't know how to make this work gracefully or I'd just submit a PR.

Thanks!

**Comment by smrq** [comment]
Quick question, are you perhaps calling `.on('error', callback)` before `.bundle()`?  I ask because this was actually a point of confusion for me at one point.

Otherwise, with this much information I'm not sure what could be going wrong.  Handling errors *should* work as usual for Browserify, and the functionality is tested.  (See: the relevant tests [(1)](https://github.com/smrq/tsify/blob/b1e879035208e573065757b6225172f36a4237d4/test/test.js#L46) and [(2)](https://github.com/smrq/tsify/blob/b1e879035208e573065757b6225172f36a4237d4/test/test.js#L65) and [the implementation](https://github.com/smrq/tsify/blob/b1e879035208e573065757b6225172f36a4237d4/test/test.js#L143))

**Comment by cherrydev** [comment]
Well, I could have sworn I tried calling `.on('error', callback)` at every possible point in the pipeline before and after `.bundle()`, and not having any luck with it.  But taking your advice and placing it immediately after .bundle() did the trick!  Thank you for your help.

**Comment by smrq** [comment]
Great!  Glad it works for you now.
