### ISSUE TITLE
Prevent browserify from aborting builds that don't typecheck

### ISSUE THREAD

**Issue by jvilk** [smrq/tsify#59]
First off: great project, but I'm having a fairly annoying issue that I hope you can help me out with.

Could you provide a simple boolean option that prevents browserify from bailing out on builds that don't type check? While generally a *Terrible No Good Very Bad Idea*, this behavior prevents me from [ignoring some fairly annoying issues with DefinitelyTyped typings caused by TypeScript 1.5 changes](https://github.com/borisyankov/DefinitelyTyped/issues/4249). It looks like there's no hope for these issues getting resolved until TypeScript 1.5.2 is released, and it also seems like `tsify` forces you to use TypeScript 1.5 (which isn't a bad thing -- `tsconfig.json` removes a ton of redundant build boilerplate).

If this is already possible, I'd greatly appreciate a pointer on how to do this.

Thanks!

**Comment by smrq** [comment]
Because of how the Browserify CLI handles pipeline errors this can only be done by using the API instead of the CLI.  Check out the API example, note the `.on('error')` that catches errors.  The process only bails out if errors get dropped on the floor (which is what the Browserify CLI does)

https://github.com/smrq/tsify#example-usage
