### ISSUE TITLE
reference path vs require

### ISSUE THREAD

**Issue by basti1253** [smrq/tsify#69]
Hi,

this isn't really a tsify issue as more a (maybe stupid) support question about how to handle typescript modules.

By using tsc as transpiler I am able to define a custom order of script inclusion.

I tried to mimic this behaviour using require and tsify but I failed to include the scripts in the exact same order as defined by using refence path. As a consequence I can't access module properties the same way as I was using tsc.

I prepared a very small repository to show my problem: https://github.com/basti1253/browserify-typescript
tsc.html => console shows 123
tsify.html: Uncaught TypeError: Cannot read property 'foo' of undefined

How do you handle this?

cheers

Sebastian

**Comment by smrq** [comment]
Hey Sebastian,

Looks like in your small example you are using *namespaces* (formerly called "internal modules") rather than *modules* (formerly called "external modules" -- sorry about the confusing terminology, but that's the way it is!)  You aren't actually gaining anything by using `tsify` if this is the case.

The module-oriented way of doing that example would be (using the newer ES6 module syntax):

#### app.ts
```ts
import { foo } from './configs/foo';
foo();
```
#### configs/foo.ts
```ts
export function foo() {
    console.log(123)
}
```

The reason for organizing your code in this way is that you don't *have* to worry about order of script includes.  Browserify handles that for you and makes sure that everything runs in the right order based on the dependency graph of your code.

**Comment by basti1253** [comment]
Hey,

thank you very much for clarification! I owe you a coffee ;) Using reexports I finally found a way how to import directories as modules. I updated the repository accordingly so maybe others may benefit. 

cheers!

Sebastian

**Comment by smrq** [comment]
Great!  Glad you were successful :)
